#!/bin/sh
# Require a Jira issue key as the Conventional Commit scope (NES-170).
#
# This is the hard gate .conform.yaml cannot provide: conform's conventional
# check treats an EMPTY scope as valid ("Scope is optional" in
# check_conventional_commit.go), so "feat: no key" passes commit-lint. conform
# still owns everything else about the message — type, case, length, trailing
# character — and this script deliberately checks ONLY the scope, so the two
# never disagree about the rest.
#
# Both the lefthook commit-msg hook and the CI commit-lint job call this file,
# so the rule has one definition rather than a copy per caller that can drift.
#
# Usage:
#   check-commit-scope.sh --file <commit-msg-file>   # local hook, one message
#   check-commit-scope.sh --range <base-ref>         # CI, base-ref..HEAD
set -eu

# Types mirror .conform.yaml. A trailing "!" (breaking change) is allowed
# between the scope and the colon.
TYPES='feat|fix|docs|chore|refactor|test|build|ci|perf|style|revert'
# Any project key, in every repo on purpose: work crosses repos, so a nestcore
# change may be tracked under a NES or an NSTR ticket.
KEY='[A-Z][A-Z0-9]+-[0-9]+'
PATTERN="^(${TYPES})\\(${KEY}\\)!?: .+"

usage() {
	echo "usage: $0 --file <commit-msg-file> | --range <base-ref>" >&2
	exit 2
}

# reject prints why a subject failed, with an example of the expected shape.
reject() {
	echo "commit-scope: $1" >&2
	echo "  subject: $2" >&2
	echo >&2
	echo "  Every commit must carry its Jira key as the Conventional Commit" >&2
	echo "  scope, so a merged change names the ticket that asked for it:" >&2
	echo >&2
	echo "    feat(NES-123): add the member pin table" >&2
	echo "    fix(NSTR-42): clamp ageBoost to non-negative" >&2
	exit 1
}

# check validates one subject line. allow_fixup is "yes" for the local hook,
# where fixup!/squash! commits are a normal part of an autosquash workflow, and
# "no" in CI, where one reaching a PR means it was never squashed away and
# would land on main as-is under a rebase merge.
check() {
	subject=$1
	allow_fixup=$2

	case $subject in
	"fixup! "* | "squash! "* | "amend! "*)
		if [ "$allow_fixup" = yes ]; then
			return 0
		fi
		reject "a fixup/squash commit must be autosquashed before review" "$subject"
		;;
	esac

	if ! printf '%s\n' "$subject" | grep -Eq "$PATTERN"; then
		reject "missing or malformed Jira key in the commit scope" "$subject"
	fi
}

case ${1:-} in
--file)
	[ $# -eq 2 ] || usage
	# The subject is the first line that is neither blank nor a comment: git
	# passes the raw file, which may open with comments (commit.template) or
	# a blank line.
	subject=$(grep -v '^#' "$2" | grep -m1 -v '^[[:space:]]*$' || true)
	[ -n "$subject" ] || reject "empty commit message" "(none)"
	check "$subject" yes
	;;
--range)
	[ $# -eq 2 ] || usage
	base=$2
	# --no-merges: a merge commit's subject is generated by git and carries no
	# scope. Rebase merges mean these are rare here, but a branch that merged
	# main into itself would otherwise fail for a commit nobody wrote.
	#
	# Bot commits are exempt because there is no ticket to name: a dependency
	# bump is raised by the bot, not asked for by a person. The author is read
	# from the commit rather than the CI actor so the exemption cannot be
	# claimed by a human pushing to a bot-opened branch. %x1f is the ASCII unit
	# separator, which cannot occur in an author name or a subject.
	git log --no-merges --format='%an%x1f%s' "${base}..HEAD" | while IFS= read -r line; do
		author=${line%%"$(printf '\037')"*}
		subject=${line#*"$(printf '\037')"}
		case $author in
		"dependabot[bot]" | "renovate[bot]" | "github-actions[bot]")
			continue
			;;
		esac
		check "$subject" no
	done
	;;
*)
	usage
	;;
esac
